# Generated by Django 2.2.5 on 2019-09-16 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_videothread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videothread',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='videothread',
            name='date_started',
        ),
        migrations.AddField(
            model_name='videothread',
            name='time_ended',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videothread',
            name='time_started',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
