# Generated by Django 2.2.5 on 2019-09-16 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190916_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videothread',
            name='time_ended',
        ),
        migrations.RemoveField(
            model_name='videothread',
            name='time_started',
        ),
        migrations.AddField(
            model_name='videothread',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='videothread',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videothread',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
